### PR TITLE
feat: add option to auto close quickfix list when no errors are found

### PR DESCRIPTION
**Pull request by jonathan-elize**
I think it would be nice to have an option to automatically close the quickfix list after fixing all the issues that might've been found. This PR is to add an option for this.

### CODE REVIEW

**Comment by dmmulroy** [comment]
This is a great idea and addition - thanks for the contribution! Before I merge, could you update the README to add the new config option here: https://github.com/dmmulroy/tsc.nvim/blob/main/README.md?plain=1#L77-L88

**Review by dmmulroy — CHANGES_REQUESTED** [review]
This is a great idea and addition - thanks for the contribution! Before I merge, could you update the README to add the new config option here: https://github.com/dmmulroy/tsc.nvim/blob/main/README.md?plain=1#L77-L88

**Comment by jonathan-elize** [comment]
Yup, I've done so in my last commit!

**Review by dmmulroy — APPROVED** [review]

**Comment by dmmulroy** [comment]
Thanks @jonathan-elize!

**Pull request merged**
